name: Lint Dockerfile

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: Dockerfile
        no-fail: true # ---->>> thêm vào dây
